Import Libraries

In [1]:
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string

Load the Data

In [2]:
from google.colab import files
uploaded = files.upload()

Saving emails.csv to emails.csv


In [3]:
# Read the CSV file
df = pd.read_csv('emails.csv')

# Print the first 5 rows of data
df.head(5)

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

Print the shape (Get the number of rows and columns)

In [4]:
df.shape

(5728, 2)

Get the Columns Names

In [5]:
df.columns

Index(['text', 'spam'], dtype='object')

Check for duplicates and remove them

In [6]:
df.drop_duplicates(inplace=True)

Show the new shape(number of rows and columns)

In [7]:
df.shape

(5695, 2)

Show the number of missing ( NAN, NaN, na) data for each column

In [9]:
df.isnull().sum()

text    0
spam    0
dtype: int64

Download the stopwords Package

In [10]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [12]:
def process_text(text):
  #1 remove punctuation
  nopunc = [char for char in text if char not in string.punctuation]
  nopunc = ''.join(nopunc)
  
  #2 remove stopwords
  clean_words = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
  
  #3 return a list of clean text words
  return clean_words

Show the tokenization ( a list of tokens also called lemmas )

In [13]:
df['text'].head().apply(process_text)

0    [Subject, naturally, irresistible, corporate, ...
1    [Subject, stock, trading, gunslinger, fanny, m...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, money, get, software, cds, software,...
Name: text, dtype: object

Example

In [14]:
message4 = 'hello world hello hello world play'
message5 = 'test test test test one hello'
print(message4)
print()

hello world hello hello world play



Convert the text to a matrix of token counts

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
bow4 = CountVectorizer(analyzer=process_text).fit_transform([[message4], [message5]])
print(bow4)
print()

print(bow4.shape)

  (0, 0)	3
  (0, 4)	2
  (0, 2)	1
  (1, 0)	1
  (1, 3)	4
  (1, 1)	1

(2, 5)


Convert a collection of text to a matrix of tokens

In [17]:
from sklearn.feature_extraction.text import CountVectorizer
messages_bow = CountVectorizer(analyzer=process_text).fit_transform(df['text'])

Split the data into 80% training and 20% testing

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(messages_bow, df['spam'], test_size=0.20, random_state = 0)

Get the Shape of messages_bow

In [19]:
messages_bow.shape

(5695, 37229)

Create and train the Naive Bayes Classifier

In [20]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(X_train, y_train)

Print The Predictions

In [21]:
print(classifier.predict(X_train))

[0 0 0 ... 0 0 0]


Print the actual values

In [22]:
print(y_train.values)

[0 0 0 ... 0 0 0]


Evaluate the model on the training data set

In [25]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(X_train)
print(classification_report(y_train, pred))
print()
print('Confusion Matrix: \n', confusion_matrix(y_train, pred))
print()
print('Accuracy: ', accuracy_score(y_train, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3457
           1       0.99      1.00      0.99      1099

    accuracy                           1.00      4556
   macro avg       0.99      1.00      1.00      4556
weighted avg       1.00      1.00      1.00      4556


Confusion Matrix: 
 [[3445   12]
 [   1 1098]]

Accuracy:  0.9971466198419666


In [26]:
print(classifier.predict(X_test))
print(y_test.values)

[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]


In [27]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(X_test)
print(classification_report(y_test, pred))
print()
print('Confusion Matrix: \n', confusion_matrix(y_test, pred))
print()
print('Accuracy: ', accuracy_score(y_test, pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       870
           1       0.97      1.00      0.98       269

    accuracy                           0.99      1139
   macro avg       0.98      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139


Confusion Matrix: 
 [[862   8]
 [  1 268]]

Accuracy:  0.9920983318700615
